// import "./globals.css";
import Link from "next/link";
import Header from "./components/header";
import { AuthProvider } from "./components/authorization";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/daisyui@5"
          rel="stylesheet"
          type="text/css"
        />
        <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
        <link
          href="https://cdn.jsdelivr.net/npm/daisyui@5.0.0/themes.css"
          rel="stylesheet"
          type="text/css"
        />
      </head>
      <body>
        <AuthProvider>
          <Header />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
